CREATE TABLE PROVINCIA(
Cod_provi NUMBER(2) PRIMARY KEY,
Nombre VARCHAR2(25) not null,
Pais  VARCHAR2(25),
CHECK(Pais in ('España','Portugal'))
 );
 
CREATE TABLE EMPRESA(
Cod_empre NUMBER(2) PRIMARY KEY,
Nombre VARCHAR2(25) DEFAULT('empresa1'),
Fecha_crea date default SYSDATE+1
 );
 
CREATE TABLE Continentes(
Cod_conti NUMBER PRIMARY KEY,
Nombre VARCHAR2(20) DEFAULT('Europa') not null
 );
 
CREATE TABLE Alumno(
Codigo NUMBER(3) PRIMARY KEY,
Nombre VARCHAR2(21) not null,
Apellido VARCHAR2(30) not null CHECK(APELLIDO=UPPER(APELLIDO),
Curso NUMBER(1) CHECK(Curso in (1,2,3),
Fecha_matri date default SYSDATE
 );
 
CREATE TABLE EMPLEADOS(
Cod_emple NUMBER(2) PRIMARY KEY,
Nombre VARCHAR2(20) not null,
Apellido VARCHAR2(25),
Salario NUMBER(7,2) CHECK(Salario>0),
FK_Cod_provi NUMBER(2) REFERENCES Provincia (Cod_provi)ON DELETE CASCADE,
FK_Cod_empre NUMBER(2) REFERENCES Empresa (Cod_empre) ON DELETE CASCADE
 );
 
 CREATE TABLE PERSONAS(
 DNI VARCHAR2(25) PRIMARY KEY,
 NOMBRE VARCHAR2(25),
 DIRECCION VARCHAR2(25),
 POBLACION VARCHAR2(25),
 CODPROVI NUMBER(2) REFERENCES PROVINCIA(COD_PROVI) ON DELETE CASCADE
 );
 
 CREATE TABLE PROVINCIAS(
 COD_PROVINCIA NUMBER(2),
 NOM_PROVINCIA VARCHAR2(25)
 );
 
 CREATE TABLE EJEMPLO1(
 DNI VARCHAR2(10) PRIMARY KEY,
 NOMBRE VARCHAR2(30) UNIQUE,
 EDAD NUMBER(2) CHECK (EDAD>17 AND EDAD<66),
 FECHA DATE DEFAULT SYSDATE
 );
 
 CREATE TABLE EJEMPLO3(
 DNI VARCHAR2(10) PRIMARY KEY NOT NULL,
 NOMBRE VARCHAR(30),
 EDAD NUMBER(2)CHECK (EDAD>4 AND EDAD<21),
 CURSO NUMBER(1) CHECK(CURSO IN (1,2,3))
 );
 
 CREATE TABLE ALUMNOS(
 CODIGO NUMBER(2) PRIMARY KEY,
 NOMBRE VARCHAR2(25) NOT NULL
 );
 
 CREATE TABLE MODULOS(
 CODIGO NUMBER(2) PRIMARY KEY,
 NOMBRE VARCHAR2(25)
 );
 
 CREATE TABLE NOTAS(
 COD_ALUMNO NUMBER(2),
 COD_MODULO NUMBER(2),
 PRIMARY KEY(COD_ALUMNO,COD_MODULO),
 NOTA NUMBER(2) CHECK(NOTA>-1 AND NOTA<11),
 CONSTRAINT ALUMNO_FK FOREIGN KEY (COD_ALUMNO) REFERENCES ALUMNOS(CODIGO),
 CONSTRAINT MODULO_FK FOREIGN KEY (COD_MODULO) REFERENCES MODULOS(CODIGO)
 );
 
 