SELECT * FROM employees

SELECT * FROM employees
WHERE JOB_ID= 'IT_PROG';

SELECT * FROM employees
WHERE salary > 6000;

--dual tabla de prueba(podemos hacer lo que queramos)
SELECT SYSDATE FROM dual;

SELECT * FROM employees
WHERE HIRE_DATE > '01/01/05';

SELECT first_name,last_name,salary
FROM employees
WHERE HIRE_DATE> '01/01/05';

CREATE TABLE DEPARTAMENTO(
dept_no NUMBER(2) not null,
denombre VARCHAR2(14),
loc  VARCHAR2(14)
 );

CREATE TABLE Empleados(
emp_no NUMBER(4) not null ,
apellido VARCHAR2(10),
oficio VARCHAR2(10),
dir NUMBER(4),
fecha_alt date ,
salario number(10),
comisión number(10),
dept_no number(2)not null
);
CREATE TABLE PROVINCIA(
Cod_provi NUMBER(2) PRIMARY KEY,
Nombre VARCHAR2(25) not null,
Pais  VARCHAR2(25),
CHECK(Pais in ('España','Portugal'))
 );
 CREATE TABLE EMPRESA(
Cod_empre NUMBER(2) PRIMARY KEY,
Nombre VARCHAR2(25) DEFAULT('empresa1'),
Fecha_crea date default SYSDATE
 );
CREATE TABLE Continentes(
Cod_conti NUMBER PRIMARY KEY,
Nombre VARCHAR2(20) DEFAULT('Europa') not null
 );
 CREATE TABLE EMPLEADOS(
Cod_emple NUMBER(2) PRIMARY KEY,
Nombre VARCHAR2(20) not null,
Apellido VARCHAR2(25),
Salario NUMBER(7,2) CHECK(Salario>0),
FK_Cod_provi NUMBER(2) REFERENCES Provincia (Cod_provi)ON DELETE CASCADE,
FK_Cod_empre NUMBER(2) REFERENCES Empresa (Cod_empre) ON DELETE CASCADE
 );
CREATE TABLE PERSONAS(
 DNI VARCHAR2(25) PRIMARY KEY,
 NOMBRE VARCHAR2(25),
 DIRECCION VARCHAR2(25),
 POBLACION VARCHAR2(25),
 CODPROVI NUMBER(2) REFERENCES PROVINCIA(COD_PROVI) ON DELETE CASCADE
 );
CREATE TABLE PROVINCIAS(
 COD_PROVINCIA NUMBER(2),
 NOM_PROVINCIA VARCHAR2(25)
 );
CREATE TABLE ALUMNOS(
 CODIGO NUMBER(2) PRIMARY KEY,
 NOMBRE VARCHAR2(25) NOT NULL
 );
 
 CREATE TABLE MODULOS(
 CODIGO NUMBER(2) PRIMARY KEY,
 NOMBRE VARCHAR2(25)
 );
CREATE TABLE NOTAS(
 COD_ALUMNO NUMBER(2),
 COD_MODULO NUMBER(2),
 PRIMARY KEY(COD_ALUMNO,COD_MODULO),
 NOTA NUMBER(2) CHECK(NOTA>-1 AND NOTA<11),
 CONSTRAINT ALUMNO_FK FOREIGN KEY (COD_ALUMNO) REFERENCES ALUMNOS(CODIGO),
 CONSTRAINT MODULO_FK FOREIGN KEY (COD_MODULO) REFERENCES MODULOS(CODIGO)
 );

